// Generated by scripts/generate-role-badges.py. Logo and Mira are untouched.
import UIKit
import NebulaSettingsContract

enum NebulaProfileBadgeArtwork {
    static func image(for badge: NebulaBadge) -> UIImage? {
        switch badge {
        case .supporter: return NebulaProfileBadgeImages.supporter
        case .star: return NebulaProfileBadgeImages.star
        default: return vectorImages[badge]
        }
    }
    private static let vectorImages: [NebulaBadge: UIImage] = {
        var result: [NebulaBadge: UIImage] = [:]
        for badge in [NebulaBadge.dev, .tester, .heart] {
            let format = UIGraphicsImageRendererFormat()
            format.scale = 3
            format.opaque = false
            result[badge] = UIGraphicsImageRenderer(size: CGSize(width: 28, height: 28), format: format).image { _ in
                draw(badge)
            }.withRenderingMode(.alwaysOriginal)
        }
        return result
    }()
    private static func color(_ rgb: UInt32) -> UIColor {
        UIColor(red: CGFloat((rgb >> 16) & 255) / 255, green: CGFloat((rgb >> 8) & 255) / 255,
                blue: CGFloat(rgb & 255) / 255, alpha: 1)
    }
    private static func draw(_ badge: NebulaBadge) {
        switch badge {
        case .dev:
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 10, y: 2))
            path.addLine(to: CGPoint(x: 18, y: 2))
            path.addQuadCurve(to: CGPoint(x: 21.5, y: 3.5), controlPoint: CGPoint(x: 20, y: 2))
            path.addLine(to: CGPoint(x: 24.5, y: 6.5))
            path.addQuadCurve(to: CGPoint(x: 26, y: 10), controlPoint: CGPoint(x: 26, y: 8))
            path.addLine(to: CGPoint(x: 26, y: 18))
            path.addQuadCurve(to: CGPoint(x: 24.5, y: 21.5), controlPoint: CGPoint(x: 26, y: 20))
            path.addLine(to: CGPoint(x: 21.5, y: 24.5))
            path.addQuadCurve(to: CGPoint(x: 18, y: 26), controlPoint: CGPoint(x: 20, y: 26))
            path.addLine(to: CGPoint(x: 10, y: 26))
            path.addQuadCurve(to: CGPoint(x: 6.5, y: 24.5), controlPoint: CGPoint(x: 8, y: 26))
            path.addLine(to: CGPoint(x: 3.5, y: 21.5))
            path.addQuadCurve(to: CGPoint(x: 2, y: 18), controlPoint: CGPoint(x: 2, y: 20))
            path.addLine(to: CGPoint(x: 2, y: 10))
            path.addQuadCurve(to: CGPoint(x: 3.5, y: 6.5), controlPoint: CGPoint(x: 2, y: 8))
            path.addLine(to: CGPoint(x: 6.5, y: 3.5))
            path.addQuadCurve(to: CGPoint(x: 10, y: 2), controlPoint: CGPoint(x: 8, y: 2))
            path.close()
            color(0x7564DD).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 10, y: 2))
            path.addLine(to: CGPoint(x: 18, y: 2))
            path.addQuadCurve(to: CGPoint(x: 21.5, y: 3.5), controlPoint: CGPoint(x: 20, y: 2))
            path.addLine(to: CGPoint(x: 24.5, y: 6.5))
            path.addLine(to: CGPoint(x: 14, y: 13))
            path.addLine(to: CGPoint(x: 3.5, y: 6.5))
            path.addLine(to: CGPoint(x: 6.5, y: 3.5))
            path.addQuadCurve(to: CGPoint(x: 10, y: 2), controlPoint: CGPoint(x: 8, y: 2))
            path.close()
            color(0x9F90F0).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 14, y: 13))
            path.addLine(to: CGPoint(x: 24.5, y: 21.5))
            path.addLine(to: CGPoint(x: 21.5, y: 24.5))
            path.addQuadCurve(to: CGPoint(x: 18, y: 26), controlPoint: CGPoint(x: 20, y: 26))
            path.addLine(to: CGPoint(x: 10, y: 26))
            path.addQuadCurve(to: CGPoint(x: 6.5, y: 24.5), controlPoint: CGPoint(x: 8, y: 26))
            path.addLine(to: CGPoint(x: 3.5, y: 21.5))
            path.close()
            color(0x5F50BB).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 9.5, y: 10.5))
            path.addLine(to: CGPoint(x: 6, y: 14))
            path.addLine(to: CGPoint(x: 9.5, y: 17.5))
            path.move(to: CGPoint(x: 18.5, y: 10.5))
            path.addLine(to: CGPoint(x: 22, y: 14))
            path.addLine(to: CGPoint(x: 18.5, y: 17.5))
            path.move(to: CGPoint(x: 15.5, y: 8.5))
            path.addLine(to: CGPoint(x: 12.5, y: 19.5))
            path.lineWidth = 2
            path.lineCapStyle = .round
            path.lineJoinStyle = .round
            color(0xFFFFFF).setStroke()
            path.stroke()
            }
        case .tester:
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 14, y: 1.5))
            path.addLine(to: CGPoint(x: 24, y: 5))
            path.addQuadCurve(to: CGPoint(x: 25, y: 8), controlPoint: CGPoint(x: 25.5, y: 5.5))
            path.addLine(to: CGPoint(x: 24, y: 16))
            path.addCurve(to: CGPoint(x: 14, y: 27), controlPoint1: CGPoint(x: 23.5, y: 21), controlPoint2: CGPoint(x: 19, y: 25))
            path.addCurve(to: CGPoint(x: 4, y: 16), controlPoint1: CGPoint(x: 9, y: 25), controlPoint2: CGPoint(x: 4.5, y: 21))
            path.addLine(to: CGPoint(x: 3, y: 8))
            path.addQuadCurve(to: CGPoint(x: 4, y: 5), controlPoint: CGPoint(x: 2.5, y: 5.5))
            path.close()
            color(0x35B6A0).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 14, y: 1.5))
            path.addLine(to: CGPoint(x: 24, y: 5))
            path.addQuadCurve(to: CGPoint(x: 25, y: 8), controlPoint: CGPoint(x: 25.5, y: 5.5))
            path.addLine(to: CGPoint(x: 14, y: 13))
            path.addLine(to: CGPoint(x: 3, y: 8))
            path.addQuadCurve(to: CGPoint(x: 4, y: 5), controlPoint: CGPoint(x: 2.5, y: 5.5))
            path.close()
            color(0x6DDEC3).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 14, y: 13))
            path.addLine(to: CGPoint(x: 24, y: 16))
            path.addCurve(to: CGPoint(x: 14, y: 27), controlPoint1: CGPoint(x: 23.5, y: 21), controlPoint2: CGPoint(x: 19, y: 25))
            path.addCurve(to: CGPoint(x: 4, y: 16), controlPoint1: CGPoint(x: 9, y: 25), controlPoint2: CGPoint(x: 4.5, y: 21))
            path.close()
            color(0x248F82).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 8, y: 14))
            path.addLine(to: CGPoint(x: 12, y: 18))
            path.addLine(to: CGPoint(x: 20, y: 10))
            path.lineWidth = 2.4
            path.lineCapStyle = .round
            path.lineJoinStyle = .round
            color(0xFFFFFF).setStroke()
            path.stroke()
            }
        case .heart:
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 14, y: 6))
            path.addCurve(to: CGPoint(x: 26, y: 10), controlPoint1: CGPoint(x: 19, y: -1), controlPoint2: CGPoint(x: 27, y: 3))
            path.addCurve(to: CGPoint(x: 14, y: 26), controlPoint1: CGPoint(x: 25.5, y: 15), controlPoint2: CGPoint(x: 20, y: 21))
            path.addCurve(to: CGPoint(x: 2, y: 10), controlPoint1: CGPoint(x: 8, y: 21), controlPoint2: CGPoint(x: 2.5, y: 15))
            path.addCurve(to: CGPoint(x: 14, y: 6), controlPoint1: CGPoint(x: 1, y: 3), controlPoint2: CGPoint(x: 9, y: -1))
            path.close()
            color(0xEC6C95).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 14, y: 6))
            path.addCurve(to: CGPoint(x: 2, y: 10), controlPoint1: CGPoint(x: 9, y: -1), controlPoint2: CGPoint(x: 1, y: 3))
            path.addCurve(to: CGPoint(x: 14, y: 26), controlPoint1: CGPoint(x: 2.5, y: 15), controlPoint2: CGPoint(x: 8, y: 21))
            path.addLine(to: CGPoint(x: 10, y: 13))
            path.close()
            color(0xF6A1BB).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 14, y: 26))
            path.addCurve(to: CGPoint(x: 26, y: 10), controlPoint1: CGPoint(x: 20, y: 21), controlPoint2: CGPoint(x: 25.5, y: 15))
            path.addLine(to: CGPoint(x: 17, y: 14))
            path.close()
            color(0xD95486).setFill()
            path.fill()
            }
            do {
            let path = UIBezierPath()
            path.move(to: CGPoint(x: 18, y: 6))
            path.addLine(to: CGPoint(x: 19.5, y: 10))
            path.addLine(to: CGPoint(x: 23, y: 11.5))
            path.addLine(to: CGPoint(x: 19.5, y: 13))
            path.addLine(to: CGPoint(x: 18, y: 17))
            path.addLine(to: CGPoint(x: 16.5, y: 13))
            path.addLine(to: CGPoint(x: 13, y: 11.5))
            path.addLine(to: CGPoint(x: 16.5, y: 10))
            path.close()
            color(0xFFF4F8).setFill()
            path.fill()
            }
        default: break
        }
    }
}
