// Generated by scripts/generate-ios-icon-packs.py.
import UIKit
import AppBundle

enum NebulaIconPackArtwork {
    static func image(symbol: String, pack: Int) -> UIImage? {
        guard pack == 1 || pack == 2 else { return nil }
        let name: String
        switch symbol {
        case "bubble.left.and.bubble.right": name = "chat"
        case "bubble.left": name = "chat"
        case "person.crop.circle": name = "person"
        case "gearshape": name = "gear"
        case "gear": name = "gear"
        case "phone": name = "phone"
        case "camera": name = "camera"
        case "pencil": name = "edit"
        case "magnifyingglass": name = "search"
        case "bookmark": name = "bookmark"
        case "folder": name = "folder"
        case "bell": name = "bell"
        case "lock": name = "lock"
        case "lock.shield": name = "lock"
        case "shield": name = "lock"
        case "video": name = "video"
        case "paperclip": name = "attach"
        case "photo": name = "photo"
        case "archivebox": name = "archive"
        case "doc.on.doc": name = "copy"
        case "trash": name = "trash"
        case "square.and.arrow.up": name = "share"
        case "globe": name = "globe"
        case "info.circle": name = "info"
        case "list.bullet": name = "list"
        case "arrow.down": name = "download"
        case "arrow.down.circle": name = "download"
        case "doc": name = "file"
        default: return nil
        }
        return UIImage(bundleImageName: "NebulaPack\(pack)_\(name)")
    }
}
