/* Local design prototype. No requests, credentials, or application preferences. */
'use strict';
const paths={
 back:'m14 5-7 7 7 7',right:'m9 5 7 7-7 7',more:'M5 12h.01M12 12h.01M19 12h.01',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',
 home:'m3 10 9-7 9 7v10H3Z M9 20v-7h6v7',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M10 2h4l1 3 3 1 3 2-1 4 1 4-3 2-3 1-1 3h-4l-1-3-3-1-3-2 1-4-1-4 3-2 3-1Z',
 shield:'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6Z m-4 9 3 3 5-6',paint:'M12 3a9 9 0 1 0 0 18h1c2 0 3-2 1-4-1-1 0-3 2-3h2c5 0 4-11-6-11 M7 9h.01M11 6h.01M16 8h.01',
 chat:'M4 4h16v12H9l-5 4Z M8 8h8M8 12h5',folder:'M3 6h7l2 2h9v12H3Z',message:'M4 5h16v11H9l-5 4Z m4 4h8m-8 4h5',user:'M8 7a4 4 0 1 0 8 0 4 4 0 0 0-8 0 M4 21v-3c0-6 16-6 16 0v3',
 tabs:'M3 4h18v16H3Z M3 14h18M7 17h.01M12 17h.01M17 17h.01',spark:'m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z',info:'M12 11v6M12 7h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',
 moon:'M20 15A9 9 0 0 1 9 3 9 9 0 1 0 20 15',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1',
 check:'m5 12 4 4L19 6',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',upload:'M12 16V4m-5 5 5-5 5 5M4 17v4h16v-4',link:'m9 15 6-6M8 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 1 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0',
 globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M3 12h18M12 3c-5 4-5 14 0 18 5-4 5-14 0-18',bolt:'m13 2-8 12h6l-1 8 9-13h-7Z',heart:'M12 21 3 12C-2 5 7 0 12 7c5-7 14-2 9 5Z',
 lock:'M6 10h12v11H6Z M8 10V6a4 4 0 0 1 8 0v4M12 14v3',glass:'M4 5h16l-3 16H7Z M6 10h12',send:'m3 10 18-7-7 18-3-8Z m0 3 10-10',clip:'m9 17 8-8a3 3 0 0 0-4-4L4 14a5 5 0 0 0 7 7L21 11',smile:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M8 9h.01M16 9h.01M8 14c2 4 6 4 8 0',
 trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',phone:'M6 3 3 5c0 8 8 16 16 16l2-3-5-4-2 2-6-6 2-2Z',sliders:'M4 5h16M4 12h16M4 19h16M8 3v4m8 3v4m-5 3v4',bell:'M6 17V9a6 6 0 0 1 12 0v8l2 2H4ZM10 22h4',copy:'M8 8h13v13H8ZM16 8V3H3v13h5'
};
const svg=(name,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.settings}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toggle=(id,title,value=false,subtitle='')=>({id,title,value,subtitle,type:'toggle'});
const select=(id,title,options,value=options[0])=>({id,title,options,value,type:'select'});
const range=(id,title,value)=>({id,title,value,type:'range'});
const nav=(route,title,subtitle='')=>({id:'nav-'+route,title,subtitle,type:'nav',route});
const action=(id,title,subtitle='')=>({id,title,subtitle,type:'action'});
const field=(id,title,value='',multiline=false)=>({id,title,value,multiline,type:'field'});
const group=(title,rows,note='')=>({title,rows,note});
const native=id=>(window.NATIVE_CONTROLS[id]||[]).map(r=>({...r}));
const pages={
 home:{title:'Настройки NebulaGram',icon:'home',color:'#3396db',description:'Ваш Telegram. Ваши настройки.',groups:[]},
 link:{title:'NebulaLink',icon:'shield',color:'#3396db',description:'Ваше подключение, прямо в Telegram.',groups:[group('Подключение',[nav('servers','Серверы','Выбор сервера и проверка задержки'),nav('subscriptions','Подписки','Добавление и обновление источников')]),group('Управление',[nav('advanced','Дополнительные настройки','Пинг, звонки и параметры ядра'),action('provider','Открыть страницу провайдера'),action('guard','NebulaGuard'),nav('linkabout','О NebulaLink')])]},
 general:{title:'Основные',icon:'settings',color:'#e99a38',description:'Маленькие настройки для удобства каждый день.',groups:[group('Приложение',[select('id-format','Формат ID',['Telegram','Bot API']),toggle('stories','Истории в списке чатов',true),toggle('history','История поиска настроек',true,'Недавно открытые параметры'),action('clear-history','Очистить историю поиска')]),group('Текст и медиа',native('general'),'Некоторые изменения применятся после перезапуска приложения.')]},
 privacy:{title:'Конфиденциальность',icon:'lock',color:'#30a76c',description:'Управляйте локальными копиями и их отображением.',groups:[group('Удалённые сообщения',[toggle('retain','Сохранять удалённые сообщения',false,'Остаются на своём месте в чате'),toggle('secret','Секретные чаты'),toggle('expiring','Исчезающие сообщения')],'Копии хранятся на устройстве. Выключение не очищает ранее сохранённое.'),group('Где сохранять',[toggle('private','Личные чаты',true),toggle('groups','Группы',true),toggle('channels','Каналы',true),toggle('bots','Боты',true)]),group('Оформление',[select('deleted-icon','Значок удалённого сообщения',['Корзина','Призрак','Крестик']),select('deleted-mark','Как выделять',['Значок','Цвет','Значок и цвет']),select('deleted-color','Цвет отметки',['Красный','Серый','Синий'])]),group('Пересылка',[toggle('forward-edit','Редактирование перед пересылкой',false),toggle('protected','Разрешить снимки и пересылку',false),toggle('forward-source','Подпись источника',true)]),group('Локальный архив',[action('archive-info','Как работает сохранение'),action('clear-archive','Очистить сохранённые копии')])]},
 appearance:{title:'Оформление',icon:'paint',color:'#8872d8',description:'Цвета, иконки и детали. Найдите свой стиль.',groups:[group('Детали интерфейса',[nav('icons','Наборы иконок','NebulaGram · Solar · iOS'),nav('avatars','Закругление аватарок'),nav('switches','Переключатели','Четыре стиля на выбор'),nav('glass','Жидкое стекло','Прозрачность, размытие и отклик')]),group('Оформление',[toggle('center-titles','Центрировать заголовки'),toggle('liquid-motion','Анимации Liquid Glass',true),...native('appearance')])]},
 tabs:{title:'Нижняя панель',icon:'tabs',color:'#3396db',description:'Нужные разделы всегда под рукой.',groups:[group('Панель и кнопки',native('tabs')),group('Вкладки',[toggle('tab-contacts','Контакты',true),toggle('tab-calls','Звонки',true),toggle('tab-chats','Чаты',true),toggle('tab-settings','Настройки',true),toggle('tab-profile','Профиль',false),select('tab-order','Порядок вкладок',['Контакты · Звонки · Чаты · Настройки','Чаты · Контакты · Звонки · Настройки'])])]},
 folders:{title:'Папки',icon:'folder',color:'#edaa34',description:'Организуйте чаты так, как удобно вам.',groups:[group('Вкладки и счётчики',[select('folder-style','Стиль папок',['Подписи','Иконки','Иконки и подписи']),...native('folders'),action('manage-folders','Настроить папки')])]},
 chats:{title:'Чаты',icon:'chat',color:'#3396db',description:'Шапка, поле ввода и жесты — в вашем стиле.',groups:[group('Шапка и поле ввода',native('chats')),group('Действия',[nav('actions','Меню действий','Звонки, поиск и быстрые команды')])]},
 messages:{title:'Сообщения',icon:'message',color:'#5e80d8',description:'Всё, из чего складывается переписка.',groups:[group('Быстрые действия',[select('double-tap','Двойной тап по своему сообщению',['Реакция','Редактировать','Ответить','Копировать текст','Ничего']),select('round-camera','Камера кружка',['Как в прошлый раз','Фронтальная','Основная','Спрашивать'])]),group('Вид сообщений',native('messages'))]},
 profile:{title:'Профиль',icon:'user',color:'#e7768f',description:'Оформление профилей и быстрые действия.',groups:[group('Оформление профиля',native('profile')),group('Поддержка',[field('donation-link','Ссылка для пожертвований'),action('save-donation','Сохранить ссылку'),action('badges','Значки профиля')])]},
 ai:{title:'ИИ-помощник',icon:'spark',color:'#26a6a0',description:'Ваш провайдер. Ваши инструкции. Ваш выбор.',groups:[group('Подключение',[toggle('ai-enabled','Включить ИИ'),select('ai-provider','Провайдер',['OpenAI · GPT','Anthropic · Claude','Google · Gemini','OpenAI-compatible']),field('ai-endpoint','Адрес API'),field('ai-key','API-ключ'),field('ai-model','Модель'),action('model-list','Выбрать модель из списка'),action('save-ai','Сохранить подключение'),action('remove-key','Удалить сохранённый ключ')]),group('Инструкции',[field('ai-prompt','Системный промпт','Отвечай кратко и на русском',true),action('save-prompt','Сохранить инструкции')]),group('Запрос',[field('ai-request','Сообщение для ИИ','',true),action('ai-send','Отправить запрос')],'В превью запросы не отправляются. Не вводите настоящий API-ключ.')]},
 about:{title:'О приложении',icon:'info',color:'#8995a6',description:'Ваш Telegram. Ваш стиль. Ваше подключение.',groups:[group('Приложение',[nav('updates','Обновления NebulaGram'),action('version','Версия приложения','Демонстрационный экран'),action('package','Пакет приложения','app.nebulagram.messenger')]),group('Ссылки',[action('github','GitHub'),action('releases','Релизы'),action('community','Сообщество'),action('license','Лицензия · GPL-2.0')]),group('Компоненты',[action('telegram','Telegram для Android'),action('xray','Xray-core')])]},
 icons:{title:'Наборы иконок',parent:'appearance',icon:'paint',color:'#8872d8',description:'Один язык деталей для всего интерфейса.',groups:[group('Выберите набор',[select('icon-pack','Стиль иконок',['NebulaGram','Solar','iOS Outline'])])]},
 avatars:{title:'Аватарки',parent:'appearance',icon:'user',color:'#e7768f',description:'От мягкого квадрата до привычного круга.',groups:[group('Форма',[range('avatar-round','Закругление',100)])]},
 switches:{title:'Переключатели',parent:'appearance',icon:'sliders',color:'#8872d8',description:'Знакомые элементы управления в вашем стиле.',groups:[group('Стиль',[select('switch-style','Вид переключателей',['Material','iOS','One UI','Android'])])]},
 glass:{title:'Жидкое стекло',parent:'appearance',icon:'glass',color:'#75a7c0',description:'Лёгкость и глубина — с вашим балансом эффектов.',groups:[group('Эффекты',[toggle('glass-custom','Настроить стекло'),range('opacity','Прозрачность',37),range('blur','Размытие',40),range('refraction','Преломление',44),toggle('highlights','Блики',true),select('glass-quality','Качество стекла',['Автоматически','Полное','Облегчённое'])],'Авто снижает нагрузку при энергосбережении и нагреве. Ваши параметры сохраняются.'),group('Отклик',[toggle('haptics','Виброотклик стекла',true),range('haptic-strength','Сила отклика',50),action('try-haptics','Попробовать отклик')])]},
 actions:{title:'Меню действий',parent:'chats',icon:'sliders',color:'#3396db',description:'Соберите удобное меню для каждого чата.',groups:[group('Пункты меню',native('actions'))]},
 servers:{title:'Серверы',parent:'link',icon:'globe',color:'#3396db',description:'Источники, фильтры и выбор подключения.',groups:[group('Источники',[nav('subscriptions','Подписки'),action('import-server','Импорт конфигурации')]),group('Список серверов',[select('server','Выбранный сервер',['Амстердам · DEMO','Хельсинки · DEMO','Франкфурт · DEMO']),select('protocol','Протокол',['Все протоколы','VLESS','VMess','Trojan','Shadowsocks']),select('sort','Сортировка',['Порядок подписки','По задержке']),action('ping','Проверить задержку')],'Серверы вымышлены. Измерения и сетевые подключения не выполняются.')]},
 subscriptions:{title:'Подписки',parent:'link',icon:'folder',color:'#edaa34',description:'Ваши источники подключения в одном месте.',groups:[group('Добавить источник',[field('subscription-name','Название подписки'),field('subscription-url','Ссылка на подписку'),action('save-subscription','Добавить подписку')]),group('Управление',[action('refresh-subscriptions','Обновить все подписки'),action('manual-keys','Ручные ключи')])]},
 advanced:{title:'Параметры NebulaLink',parent:'link',icon:'sliders',color:'#3396db',description:'Точная настройка подключения и поведения.',groups:[group('Проверка задержки',[select('ping-method','Тип пинга',['Nimbo Ping','TCP','HTTP GET','URL']),field('hwid','HWID'),toggle('refresh-start','Обновлять подписки при запуске'),toggle('auto-ping','Автоматическая проверка задержки')]),group('Звонки',[action('call-state','Состояние звонка'),toggle('route-calls','Звонки через NebulaLink',true)]),group('Ядро',[toggle('switch-failure','Менять сервер при сбое'),toggle('dual-core','Оба ядра одновременно'),field('socks-port','Локальный SOCKS-порт','10808'),field('dns','DNS внутри туннеля'),action('core-versions','Версии компонентов')]),group('Кнопка на главной',[toggle('link-shortcut','Кнопка NebulaLink',true),toggle('link-ping','Показывать пинг',true),toggle('link-server','Показывать сервер',true)])]},
 linkabout:{title:'О NebulaLink',parent:'link',icon:'shield',color:'#3396db',description:'Подключение через выбранный вами сервер.',groups:[group('Инструменты',[action('versions','Версии компонентов'),action('logs','Экспорт журналов'),action('reset-link','Сбросить настройки NebulaLink')])]},
 updates:{title:'Обновления',parent:'about',icon:'download',color:'#3396db',description:'Новые возможности и улучшения NebulaGram.',groups:[group('Обновления приложения',[action('check-update','Проверить обновления'),toggle('auto-update','Проверять автоматически',true),action('release-notes','Что нового')])]},
 transfer:{title:'Перенос настроек',icon:'copy',color:'#8995a6',description:'Сохраните своё оформление или перенесите его.',groups:[group('Настройки превью',[action('export','Экспорт настроек превью'),action('import','Импорт настроек превью')],'Файл содержит только демонстрационные параметры этого превью. Формат приложения не используется.')]}
};
const homeGroups=[['Подключение',['link']],['Приложение',['general','privacy','appearance']],['Навигация',['tabs','folders']],['Чаты и профиль',['chats','messages','profile']],['Инструменты',['ai','about']]];
const short={link:'Серверы, подписки и подключение',general:'Поведение, текст и медиа',privacy:'Локальные копии и пересылка',appearance:'Цвета, иконки и эффекты',tabs:'Вкладки и быстрые действия',folders:'Стиль вкладок и счётчики',chats:'Шапка, жесты и поле ввода',messages:'Внешний вид и действия',profile:'Аватарки, фон и детали',ai:'Gemini · Claude · GPT',about:'Версия, обновления и ссылки'};
pages.home.groups=homeGroups.map(([title,ids])=>group(title,ids.map(id=>nav(id,pages[id].title,short[id]))));
const controls=new Map();Object.entries(pages).forEach(([page,p])=>p.groups.forEach(g=>g.rows.forEach(r=>{if(r.type!=='nav')controls.set(r.id,{...r,page});})));
const state=Object.fromEntries([...controls].map(([id,r])=>[id,r.value]));
const defaults={...state};let route='home',aiTab=0,accent='#268fda',timer,focused='',history=[];
const $=id=>document.getElementById(id);
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('visible'),2800);}
function go(id,push=true){if(!pages[id])id='home';if(push&&id!==route)history.push(route);route=id;window.history.replaceState(null,'','#'+id);render();$('screen').scrollTop=0;}
function back(){go(history.pop()||pages[route].parent||'home',false);}
function row(r,p){const isNav=r.type==='nav',meta=isNav?pages[r.route]:p;const tile=isNav?`<span class="row-icon" style="--tile:${meta.color}">${svg(meta.icon)}</span>`:'';let trailing='';if(isNav)trailing=svg('right','chevron');if(r.type==='toggle')trailing=`<span class="switch ${state[r.id]?'on':''}"></span>`;if(r.type==='select')trailing=`<span class="value">${esc(state[r.id])}</span>${svg('right','chevron')}`;
 if(r.type==='range')return `<div class="range-row"><label class="range-label" for="${r.id}">${esc(r.title)}<output id="out-${r.id}">${state[r.id]}%</output></label><input id="${r.id}" data-range="${r.id}" type="range" min="0" max="100" value="${state[r.id]}"></div>`;
 if(r.type==='field')return `<label class="field"><span>${esc(r.title)}</span>${r.multiline?`<textarea data-field="${r.id}" placeholder="${r.id==='ai-request'?'Напишите вопрос или вставьте текст':'Введите текст'}">${esc(state[r.id])}</textarea>`:`<input data-field="${r.id}" value="${esc(state[r.id])}" type="${r.id==='ai-key'?'password':'text'}" autocomplete="off" placeholder="${r.id==='ai-key'?'Только демонстрационный ключ':'Введите значение'}">`}</label>`;
 return `<button class="row ${isNav?'':'no-icon'} ${r.id.startsWith('clear-')||r.id==='remove-key'?'danger':''}" data-${isNav?'nav':'control'}="${isNav?r.route:r.id}" ${r.type==='toggle'?`role="switch" aria-checked="${!!state[r.id]}"`:''} id="row-${r.id}">${tile}<span class="row-copy"><span class="row-title">${esc(r.title)}</span>${r.subtitle?`<span class="row-subtitle" style="display:block">${esc(r.subtitle)}</span>`:''}</span>${trailing}</button>`;
}
function groupHtml(g,p){return `${g.title?`<div class="section-label">${esc(g.title)}</div>`:''}<div class="group">${g.rows.map(r=>row(r,p)).join('')}</div>${g.note?`<p class="note">${esc(g.note)}</p>`:''}`;}
function hero(p){return `<div class="hero"><div class="hero-top"><span class="hero-icon">${svg(p.icon)}</span><h3>${esc(p.title)}</h3></div><p>${esc(p.description)}</p></div>`;}
function chat(){const seconds=state.NebulaSeconds?':24':'';return `<div class="chat-preview"><div class="chat-top">${svg('back')}<span class="avatar">А</span><div><b>Аня</b><small>в сети</small></div>${svg('more','dots')}</div><div class="chat-messages"><div class="date">19 сентября</div><div class="bubble">Как тебе новое оформление?<small>9:41${seconds}</small></div><div class="bubble out">Всё на своих местах.<br>И немного больше меня 🙂<small>9:41${seconds} &nbsp;✓✓</small></div></div><div class="chat-composer">${svg('clip')}<span>Сообщение</span>${svg('smile')}<span class="send">${svg('send')}</span></div></div>`;}
function badgeGallery(){return `<div class="badge-gallery" aria-label="Собственные значки NebulaGram">${[['supporter','Поддержка'],['dev','Разработчик'],['tester','Тестировщик'],['star','Звезда'],['heart','Спасибо']].map(([id,title])=>`<div>${window.NEBULA_BADGES[id]}<small>${title}</small></div>`).join('')}</div>`;}
let previewFolder = 'Все чаты';
function preview(p){if(['chats','messages','glass'].includes(route))return `<div class="mini-preview">${chat()}</div>`;if(['profile','avatars'].includes(route))return '<div class="profile-preview"><div class="avatar">А</div><b>Аня</b><small>была недавно</small></div>'+badgeGallery();if(route==='folders')return '<div class="group folder-scene"><div class="folder-tabs"></div><div class="folder-chats" aria-hidden="true"><i></i><i></i></div></div>';if(route==='tabs')return `<div class="tab-sample">${[['user','Контакты'],['phone','Звонки'],['chat','Чаты'],['settings','Настройки']].map(([i,t])=>`<span>${svg(i)}${esc(t)}</span>`).join('')}</div>`;if(route==='icons')return `<div class="tab-sample">${['chat','folder','user','phone','settings'].map(i=>`<span>${svg(i)}</span>`).join('')}</div>`;if(route==='switches')return `<div class="group"><div class="row"><span class="row-copy">Образец переключателя</span><span class="switch"></span><span class="switch on"></span></div></div>`;return '';}
function render(){const p=pages[route];$('page-title').textContent=p.title;$('breadcrumb').textContent=route==='home'?'Настройки':`Настройки / ${p.title}`;$('back').innerHTML=svg('back');$('back').style.visibility=route==='home'?'hidden':'visible';$('more').innerHTML=svg('more');$('theme').innerHTML=svg(document.body.classList.contains('dark')?'sun':'moon');
 $('navigation').innerHTML=[['',['home']],...homeGroups].map(([label,ids])=>`${label?`<div class="nav-group">${label.toUpperCase()}</div>`:''}${ids.map(id=>`<button class="nav-item ${route===id||pages[route].parent===id?'active':''}" data-nav="${id}" ${route===id?'aria-current="page"':''}>${svg(pages[id].icon)}${id==='home'?'Все настройки':pages[id].title}</button>`).join('')}`).join('');
 let header=route==='home'?`<label class="search">${svg('search')}<input id="search" type="search" placeholder="Поиск настроек" aria-label="Поиск настроек"></label><div id="search-results"></div>`:hero(p);
 if(route==='link')header=`<div class="connect-card"><span class="status-chip">Демо-подключение</span><div class="connect-symbol">${svg('shield')}</div><h3>${state.connected?'Подключение включено':'Готов к подключению'}</h3><p>Выберите сервер и включите NebulaLink</p><button class="primary" data-action="connect">${state.connected?'Отключить':'Подключиться'}</button></div>`;
 if(route==='appearance')header+=`<div class="section-label">Тема превью</div><div class="group"><div class="theme-cards"><button class="theme-card ${!document.body.classList.contains('dark')?'selected':''}" data-theme="light"><div class="theme-mini"><i></i><i></i></div>Светлая</button><button class="theme-card ${document.body.classList.contains('dark')?'selected':''}" data-theme="dark"><div class="theme-mini night"><i></i><i></i></div>Тёмная</button></div></div>`;
 if(route==='ai')header+=`<div class="segmented">${['Подключение','Инструкции','Запрос'].map((t,i)=>`<button data-ai-tab="${i}" class="${i===aiTab?'active':''}">${t}</button>`).join('')}</div>`;
 const groups=route==='ai'?[p.groups[aiTab]]:p.groups;
 $('screen').innerHTML=header+`<div id="page-groups">${preview(p)}${groups.map(g=>groupHtml(g,p)).join('')}${route==='home'?'<div class="footer-brand"><img src="../icon/icon-rounded.png" alt="">NebulaGram<br>Ваш Telegram. Ваш стиль.</div>':''}</div>`;
 $('live-chat').innerHTML=chat();$('note-icon').innerHTML=svg(p.icon);$('note-title').textContent=route==='home'?'Привычно с первого касания':p.title;$('note-text').textContent=route==='home'?'Разделы, цветные значки и спокойные поверхности. Всё нужное — на своём месте.':p.description;
 $('swatches').innerHTML=['#268fda','#26a6a0','#8872d8','#e7768f','#d89a36'].map(c=>`<button class="swatch ${c===accent?'selected':''}" data-accent="${c}" style="--swatch:${c}" aria-label="${({'#268fda':'Синий','#26a6a0':'Бирюзовый','#8872d8':'Сиреневый','#e7768f':'Розовый','#d89a36':'Золотой'})[c]} акцент" aria-pressed="${c===accent}"></button>`).join('');
 applyVisuals();if(focused){const target=$('row-'+focused);if(target){target.scrollIntoView({block:'center'});target.classList.add('highlight');target.focus({preventScroll:true});}focused='';}
}
function applyVisuals(){
 document.documentElement.style.setProperty('--avatar-radius',`${state['avatar-round']/2}%`);
 document.body.dataset.switchStyle=state['switch-style'];
 document.querySelectorAll('.chat-preview .chat-top').forEach(e=>{
  e.style.margin=state.NebulaFloatingHeader?'8px 8px 0':'0';
  e.style.borderRadius=state.NebulaFloatingHeader?'14px':'0';
  if(route==='glass'&&state['glass-custom']){
   e.style.opacity=String(1-state.opacity/150);
   e.style.backdropFilter=`blur(${state.blur/4}px)`;
   e.style.boxShadow=state.highlights?'inset 0 0 0 1px #ffffff88':'none';
  }else{e.style.opacity='';e.style.backdropFilter='';e.style.boxShadow='';}
 });
 document.querySelectorAll('.chat-composer').forEach(e=>{e.style.margin=state.NebulaIosComposer?'0 8px 8px':'0';e.style.borderRadius=state.NebulaIosComposer?'20px':'0';});
 document.querySelectorAll('.bubble small').forEach(e=>{e.textContent='9:41'+(state.NebulaSeconds?':24':'')+(e.closest('.out')?'  ✓✓':'');});
 document.querySelectorAll('.folder-tabs').forEach(e=>{
  const showText=state['folder-style']!=='Иконки',showIcon=state['folder-style']!=='Подписи';
  const folders=[['Все чаты','chat','7'],['Личные','user',''],['Группы','folder',''],['Каналы','chat','']].filter((_,i)=>i!==0||!state.NebulaHideAllChats);
  if(!folders.some(([t])=>t===previewFolder))previewFolder=folders[0][0];
  e.closest('.folder-scene').classList.toggle('bottom',!!state.NebulaFolderTabsBottom);
  e.innerHTML=folders.map(([t,i,c])=>`<button data-folder="${t}" aria-pressed="${t===previewFolder}" class="${t===previewFolder?'selected':''} ${state.NebulaFolderOutline?'outlined':''}">${showIcon?svg(i):''}${showText?t:''}${c&&!state.NebulaHideTabCounters?`<em>${c}</em>`:''}</button>`).join('');
 });
 if(route==='tabs')document.querySelector('.tab-sample').innerHTML=[['user','Контакты','tab-contacts'],['phone','Звонки','tab-calls'],['chat','Чаты','tab-chats'],['settings','Настройки','tab-settings'],['user','Профиль','tab-profile']].filter(x=>state[x[2]]).map(([i,t])=>`<span>${svg(i)}${state.NebulaTabLabels?t:''}</span>`).join('');
 document.querySelectorAll('.chat-preview svg').forEach(e=>{e.style.strokeWidth=state['icon-pack']==='Solar'?'1.4':'1.75'});
}
function search(query){const normalize=s=>s.toLocaleLowerCase('ru').replaceAll('ё','е');const words=normalize(query).trim().split(/\s+/).filter(Boolean);$('page-groups').hidden=!!words.length;const results=$('search-results');if(!words.length){results.innerHTML='';return;}const found=[];Object.entries(pages).forEach(([id,p])=>{if(id==='home')return;if(words.every(w=>normalize(p.title+' '+p.description).includes(w)))found.push(nav(id,p.title,p.description));p.groups.forEach(g=>g.rows.forEach(r=>{if(r.type!=='nav'&&words.every(w=>normalize(r.title+' '+(r.subtitle||'')).includes(w)))found.push({...nav(id,r.title,p.title),id:'result-'+r.id,focus:r.id});}));});results.innerHTML=found.length?`<div class="section-label">Найдено: ${found.length}</div><div class="group">${found.map(r=>row(r,pages[r.route]).replace('data-nav=',`${r.focus?`data-focus="${r.focus}" `:''}data-nav=`)).join('')}</div>`:`<div class="empty">${svg('search')}Ничего не найдено<p>Попробуйте «папки», «стекло» или «сообщения».</p></div>`;}
function sheet(title,html){$('sheet-title').textContent=title;$('sheet-body').innerHTML=html;$('sheet').showModal();}
function choose(r){sheet(r.title,r.options.map(v=>`<button type="button" class="sheet-option ${v===state[r.id]?'selected':''}" data-choice="${esc(v)}" data-for="${r.id}">${esc(v)}${v===state[r.id]?svg('check'):''}</button>`).join(''));}
function actionClick(id){if(id==='export'){const blob=new Blob([JSON.stringify({format:'NebulaGram-design-preview',version:1,values:state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='nebulagram-preview.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Настройки превью экспортированы');return;}if(id==='import'){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>100000)throw Error();const data=JSON.parse(await file.text());if(data.format!=='NebulaGram-design-preview'||data.version!==1||!data.values||typeof data.values!=='object')throw Error();const next={};for(const [key,r]of controls){const v=data.values[key];if(v===undefined)continue;if(r.type==='toggle'&&typeof v==='boolean'||r.type==='select'&&r.options.includes(v)||r.type==='range'&&Number.isFinite(v)&&v>=0&&v<=100||r.type==='field'&&typeof v==='string'&&v.length<=20000)next[key]=v;else if(['toggle','select','range','field'].includes(r.type))throw Error();}Object.assign(state,next);render();toast('Настройки превью импортированы');}catch{toast('Не удалось прочитать файл настроек превью');}};input.click();return;}
 if(id==='clear-history'||id==='clear-archive'||id==='reset-link'||id==='remove-key'){sheet('Подтвердите действие',`<p class="sheet-message">Изменятся только демонстрационные данные превью.</p><button type="button" class="primary" data-confirm="${id}">Подтвердить</button>`);return;}
 if(id==='archive-info'){sheet('Как работает сохранение','<p class="sheet-message">Полученные сообщения остаются локально. Уже загруженные вложения могут удаляться стандартной очисткой кэша Telegram. Выключение сохранения не удаляет существующие копии.</p>');return;}
 if(id==='try-haptics'){toast('В приложении здесь срабатывает виброотклик');return;}
 if(id==='save-ai'||id==='save-prompt'||id==='save-donation'){toast('Сохранено в текущем превью');return;}
 sheet(controls.get(id)?.title||'Предпросмотр','<p class="sheet-message">Этот экран показывает дизайн. Действие доступно в приложении; в браузерном превью оно не выполняется.</p>');
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.folder){previewFolder=b.dataset.folder;applyVisuals();return;}if(b.dataset.nav){focused=b.dataset.focus||'';go(b.dataset.nav);return;}if(b.dataset.control){const r=controls.get(b.dataset.control);if(r.type==='toggle'){state[r.id]=!state[r.id];b.setAttribute('aria-checked',!!state[r.id]);b.querySelector('.switch').classList.toggle('on',!!state[r.id]);$('live-chat').innerHTML=chat();applyVisuals();}else if(r.type==='select')choose(r);else actionClick(r.id);return;}if(b.dataset.choice){state[b.dataset.for]=b.dataset.choice;$('sheet').close();const y=$('screen').scrollTop;render();$('screen').scrollTop=y;return;}if(b.dataset.theme){document.body.classList.toggle('dark',b.dataset.theme==='dark');render();return;}if(b.dataset.accent){accent=b.dataset.accent;document.documentElement.style.setProperty('--accent',accent);render();return;}if(b.dataset.aiTab!==undefined){aiTab=Number(b.dataset.aiTab);render();return;}if(b.dataset.action==='connect'){state.connected=!state.connected;render();toast('Демонстрация: реального подключения нет');return;}if(b.dataset.confirm){if(b.dataset.confirm==='remove-key')state['ai-key']='';$('sheet').close();render();toast('Демонстрационные данные очищены');}});
document.addEventListener('input',e=>{if(e.target.id==='search')search(e.target.value);if(e.target.dataset.field)state[e.target.dataset.field]=e.target.value;if(e.target.dataset.range){const id=e.target.dataset.range;state[id]=Number(e.target.value);$('out-'+id).textContent=state[id]+'%';applyVisuals();}});
$('back').onclick=back;$('more').onclick=()=>go('transfer');$('theme').onclick=()=>{document.body.classList.toggle('dark');const y=$('screen').scrollTop;render();$('screen').scrollTop=y;};$('reset').onclick=()=>{Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,defaults);accent='#268fda';document.documentElement.style.setProperty('--accent',accent);render();toast('Параметры превью сброшены');};
$('sheet').addEventListener('click',e=>{if(e.target===$('sheet')){const r=$('sheet').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('sheet').close();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('sheet').open&&route!=='home')back();});
window.addEventListener('hashchange',()=>go(location.hash.slice(1)||'home',false));
go(location.hash.slice(1)||'home',false);
