"""Keep the preview's native toggle labels aligned with Android resources."""
import json
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
UI = ROOT / 'platform/android/overlay/TMessagesProj/src/main/java/app/nebulagram/ui'
RES = ROOT / 'platform/android/overlay/TMessagesProj/src/main/res'
strings = {}
for locale in ('values', 'values-ru'):
    for path in sorted((RES / locale).glob('strings*.xml')):
        for item in ET.parse(path).getroot().findall('string'):
            strings[item.attrib['name']] = ''.join(item.itertext()).replace('\\n', ' ').replace("\\'", "'")
source = (UI / 'NebulaSectionFragment.java').read_text(encoding='utf-8')
result = {}
for method, route in [('buildAppearance','appearance'),('buildChats','chats'),('buildTabs','tabs'),('buildFolders','folders'),('buildMessages','messages'),('buildProfile','profile'),('buildGeneral','general'),('buildChatActions','actions')]:
    start = source.index('private void ' + method + '(')
    end = source.find('\n    private ', start + 20)
    body = source[start:end if end != -1 else len(source)]
    rows = []
    for match in re.finditer(r'toggle\(context,\s*R.drawable.\w+,\s*R.string.(\w+),\s*R.string.(\w+)', body):
        title, subtitle = match.groups()
        rows.append({'id': title, 'title': strings[title], 'subtitle': strings[subtitle], 'type':'toggle', 'value': title in {'NebulaFloatingHeader','NebulaAdaptiveHeader','NebulaBottomBarTitle','NebulaTabLabels','NebulaBigEmoji','NebulaReplyBackground','NebulaReplyColors','NebulaProfileChannel','NebulaProfileBirthday','NebulaStreamMedia'}})
    result[route] = rows
target = Path(__file__).with_name('native-controls.js')
target.write_text('// Generated by generate-controls.py. Values are demonstration state.\nwindow.NATIVE_CONTROLS = ' + json.dumps(result, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Generated {sum(map(len,result.values()))} native controls in {len(result)} sections')
