#!/usr/bin/env python3
"""Embed the exact Android branded PNGs in the iOS module (no image conversion)."""
import argparse
import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'platform/android/overlay/TMessagesProj/src/main/res/drawable-nodpi'
DEST = ROOT / 'platform/ios/overlay/submodules/TelegramUI/Components/PeerInfo/PeerInfoScreen/Sources/NebulaProfileBadgeImages.swift'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = '// Generated by platform/ios/tools/generate-badge-artwork.py. Do not edit.\nimport UIKit\n\nenum NebulaProfileBadgeImages {\n'
    for kind in ['supporter', 'star']:
        data = (SOURCE / f'nebula_badge_{kind}.png').read_bytes()
        assert data[:8] == b'\x89PNG\r\n\x1a\n'
        value = base64.b64encode(data).decode('ascii')
        text += f'    static let {kind}: UIImage? = Data(base64Encoded: "{value}").flatMap {{ UIImage(data: $0)?.withRenderingMode(.alwaysOriginal) }}\n'
    text += '}\n'
    if args.check:
        if not DEST.exists() or DEST.read_text(encoding='utf-8') != text:
            raise SystemExit('Outdated iOS badge images; run generate-badge-artwork.py')
    else:
        DEST.parent.mkdir(parents=True, exist_ok=True)
        DEST.write_text(text, encoding='utf-8', newline='\n')
    print('OK: iOS embeds the exact Android supporter and selected Mira PNGs')


if __name__ == '__main__':
    main()
