#!/usr/bin/env python3
"""Mirror the tested Swift contract into Bazel; embed the canonical JSON catalog."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'platform/ios/NebulaSettingsContract/Sources/NebulaSettingsContract'
DEST = ROOT / 'platform/ios/overlay/submodules/NebulaSettingsContract/Sources'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = {DEST / p.name: p.read_text(encoding='utf-8') for p in SOURCE.glob('*.swift')}
    catalog = (ROOT / 'shared/settings/catalog.json').read_text(encoding='utf-8').rstrip()
    outputs[DEST / 'NebulaEmbeddedCatalog.swift'] = (
        '// Generated by platform/ios/tools/generate-overlay.py. Do not edit.\n'
        'enum NebulaEmbeddedCatalog {\n    static let json = #"""\n'
        + catalog + '\n"""#\n}\n')
    stale = set(DEST.glob('*.swift')) - set(outputs)
    if stale:
        raise SystemExit(f'Unexpected generated sources (review manually): {sorted(stale)}')
    for path, expected in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != expected:
                raise SystemExit(f'Outdated generated source: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding='utf-8', newline='\n')
    print(f'OK: {len(outputs)} Bazel contract sources match the Swift package and catalog')


if __name__ == '__main__':
    main()
