// Generated by scripts/generate-settings-icons.py.
package app.nebulagram.ui;
import org.telegram.messenger.R;
final class NebulaSettingsIcons {
    static int resource(int original) {
        if (original == R.drawable.msg_settings) return R.drawable.nebula_settings_general;
        if (original == R.drawable.msg_settings_old) return R.drawable.nebula_settings_general;
        if (original == R.drawable.msg_secret) return R.drawable.nebula_settings_privacy;
        if (original == R.drawable.msg_permissions) return R.drawable.nebula_settings_privacy;
        if (original == R.drawable.msg_customize) return R.drawable.nebula_settings_appearance;
        if (original == R.drawable.msg_list) return R.drawable.nebula_settings_navigation;
        if (original == R.drawable.files_folder) return R.drawable.nebula_settings_folder;
        if (original == R.drawable.msg_folders) return R.drawable.nebula_settings_folder;
        if (original == R.drawable.msg_discussion) return R.drawable.nebula_settings_chat;
        if (original == R.drawable.msg_discuss) return R.drawable.nebula_settings_chat;
        if (original == R.drawable.menu_reply) return R.drawable.nebula_settings_messages;
        if (original == R.drawable.msg_openprofile) return R.drawable.nebula_settings_profile;
        if (original == R.drawable.settings_account) return R.drawable.nebula_settings_profile;
        if (original == R.drawable.msg_emoji_smiles) return R.drawable.nebula_settings_ai;
        if (original == R.drawable.msg_info) return R.drawable.nebula_settings_about;
        if (original == R.drawable.msg_link) return R.drawable.nebula_settings_link;
        return NebulaIcons.previewResource(original, 1);
    }
}
