// Generated by scripts/generate-settings-icons.py.
package app.nebulagram.ui;
import org.telegram.messenger.R;
public final class NebulaSettingsIcons {
    public static int resource(int original) {
        if (NebulaIcons.pack() != 0) {
            if (original == R.drawable.nebula_settings_general) return R.drawable.msg_settings;
            if (original == R.drawable.nebula_settings_privacy) return R.drawable.msg_secret;
            if (original == R.drawable.nebula_settings_appearance) return R.drawable.msg_customize;
            if (original == R.drawable.nebula_settings_navigation) return R.drawable.msg_list;
            if (original == R.drawable.nebula_settings_folder) return R.drawable.files_folder;
            if (original == R.drawable.nebula_settings_chat) return R.drawable.msg_discussion;
            if (original == R.drawable.nebula_settings_messages) return R.drawable.menu_reply;
            if (original == R.drawable.nebula_settings_profile) return R.drawable.msg_openprofile;
            if (original == R.drawable.nebula_settings_sync) return R.drawable.msg_saved;
            if (original == R.drawable.nebula_settings_tasks) return R.drawable.msg_calendar;
            if (original == R.drawable.nebula_settings_ai) return R.drawable.msg_emoji_smiles;
            if (original == R.drawable.nebula_settings_about) return R.drawable.msg_info;
            if (original == R.drawable.nebula_settings_link) return R.drawable.msg_link;
            return original;
        }
        if (original == R.drawable.msg_settings) return R.drawable.nebula_settings_general;
        if (original == R.drawable.msg_settings_old) return R.drawable.nebula_settings_general;
        if (original == R.drawable.msg_secret) return R.drawable.nebula_settings_privacy;
        if (original == R.drawable.msg_permissions) return R.drawable.nebula_settings_privacy;
        if (original == R.drawable.msg_customize) return R.drawable.nebula_settings_appearance;
        if (original == R.drawable.msg_list) return R.drawable.nebula_settings_navigation;
        if (original == R.drawable.files_folder) return R.drawable.nebula_settings_folder;
        if (original == R.drawable.msg_folders) return R.drawable.nebula_settings_folder;
        if (original == R.drawable.msg_discussion) return R.drawable.nebula_settings_chat;
        if (original == R.drawable.msg_discuss) return R.drawable.nebula_settings_chat;
        if (original == R.drawable.menu_reply) return R.drawable.nebula_settings_messages;
        if (original == R.drawable.msg_openprofile) return R.drawable.nebula_settings_profile;
        if (original == R.drawable.settings_account) return R.drawable.nebula_settings_profile;
        if (original == R.drawable.nebula_settings_chat_lock) return R.drawable.nebula_settings_chat_lock;
        if (original == R.drawable.nebula_settings_app_icon) return R.drawable.nebula_settings_app_icon;
        if (original == R.drawable.nebula_settings_text_tools) return R.drawable.nebula_settings_text_tools;
        if (original == R.drawable.msg_saved) return R.drawable.nebula_settings_sync;
        if (original == R.drawable.msg_calendar) return R.drawable.nebula_settings_tasks;
        if (original == R.drawable.msg_emoji_smiles) return R.drawable.nebula_settings_ai;
        if (original == R.drawable.msg_info) return R.drawable.nebula_settings_about;
        if (original == R.drawable.msg_link) return R.drawable.nebula_settings_link;
        return NebulaIcons.previewResource(original, 1);
    }

    public static int telegramResource(int original) {
        if (NebulaIcons.pack() != 0) return original;
        if (original == R.drawable.settings_privacy) return R.drawable.nebula_settings_privacy;
        if (original == R.drawable.msg2_secret) return R.drawable.nebula_settings_privacy;
        if (original == R.drawable.settings_folders) return R.drawable.nebula_settings_folder;
        if (original == R.drawable.msg2_folder) return R.drawable.nebula_settings_folder;
        if (original == R.drawable.settings_chat) return R.drawable.nebula_settings_chat;
        if (original == R.drawable.msg2_discussion) return R.drawable.nebula_settings_chat;
        if (original == R.drawable.settings_account) return R.drawable.nebula_settings_profile;
        if (original == R.drawable.settings_features) return R.drawable.nebula_settings_ai;
        if (original == R.drawable.settings_faq) return R.drawable.nebula_settings_about;
        if (original == R.drawable.msg2_help) return R.drawable.nebula_settings_about;
        if (original == R.drawable.settings_sounds) return R.drawable.nebula_settings_notifications;
        if (original == R.drawable.msg2_notifications) return R.drawable.nebula_settings_notifications;
        if (original == R.drawable.settings_data) return R.drawable.nebula_settings_data;
        if (original == R.drawable.msg2_data) return R.drawable.nebula_settings_data;
        if (original == R.drawable.settings_devices) return R.drawable.nebula_settings_devices;
        if (original == R.drawable.msg2_devices) return R.drawable.nebula_settings_devices;
        if (original == R.drawable.settings_power) return R.drawable.nebula_settings_energy;
        if (original == R.drawable.msg2_battery) return R.drawable.nebula_settings_energy;
        if (original == R.drawable.settings_language) return R.drawable.nebula_settings_language;
        if (original == R.drawable.msg2_language) return R.drawable.nebula_settings_language;
        if (original == R.drawable.msg2_sticker) return R.drawable.nebula_settings_stickers;
        if (original == R.drawable.settings_ask) return R.drawable.nebula_settings_help;
        if (original == R.drawable.msg2_ask_question) return R.drawable.nebula_settings_help;
        if (original == R.drawable.settings_policy) return R.drawable.nebula_settings_policy;
        if (original == R.drawable.msg2_policy) return R.drawable.nebula_settings_policy;
        if (original == R.drawable.msg_saved) return R.drawable.nebula_settings_saved;
        if (original == R.drawable.settings_premium) return R.drawable.nebula_settings_premium;
        if (original == R.drawable.settings_stars) return R.drawable.nebula_settings_premium;
        if (original == R.drawable.settings_gift) return R.drawable.nebula_settings_gift;
        if (original == R.drawable.settings_business) return R.drawable.nebula_settings_business;
        if (original == R.drawable.settings_wallet) return R.drawable.nebula_settings_wallet;
        if (original == R.drawable.settings_gram_24) return R.drawable.nebula_settings_ton;
        if (original == R.drawable.msg_addbot) return R.drawable.nebula_settings_account_add;
        return original;
    }
}
