"""Generate original, identical settings glyph paths for Android and UIKit."""
from pathlib import Path
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[1]
ANDROID = ROOT / 'platform/android/overlay/TMessagesProj/src/main'
IOS = ROOT / 'platform/ios/overlay/submodules/SettingsUI/Sources'


def swift_path(path):
    tokens = re.findall(r'[MLQCZ]|-?\d+(?:\.\d+)?', path)
    lines = []
    while tokens:
        command = tokens.pop(0)
        count = {'M': 2, 'L': 2, 'Q': 4, 'C': 6, 'Z': 0}[command]
        values, tokens = tokens[:count], tokens[count:]
        point = lambda i: f'CGPoint(x: {values[i]}, y: {values[i+1]})'
        if command == 'M': line = f'path.move(to: {point(0)})'
        elif command == 'L': line = f'path.addLine(to: {point(0)})'
        elif command == 'Q': line = f'path.addQuadCurve(to: {point(2)}, controlPoint: {point(0)})'
        elif command == 'C': line = f'path.addCurve(to: {point(4)}, controlPoint1: {point(0)}, controlPoint2: {point(2)})'
        else: line = 'path.close()'
        lines.append('            ' + line)
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    icons = json.loads((ROOT / 'design/settings/icons.json').read_text(encoding='utf-8'))
    outputs = {}
    java = '// Generated by scripts/generate-settings-icons.py.\npackage app.nebulagram.ui;\nimport org.telegram.messenger.R;\nfinal class NebulaSettingsIcons {\n    static int resource(int original) {\n'
    swift = '// Generated by scripts/generate-settings-icons.py.\nimport UIKit\n\nenum NebulaSettingsSymbols {\n    static func path(for symbol: String) -> UIBezierPath? {\n        let path = UIBezierPath()\n        switch symbol {\n'
    for name, icon in icons.items():
        outputs[ANDROID / f'res/drawable/nebula_settings_{name}.xml'] = (
            '<!-- Generated from design/settings/icons.json. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">\n'
            '    <path android:fillColor="@android:color/transparent" android:strokeColor="#FFFFFFFF" android:strokeWidth="1.8" android:strokeLineCap="round" android:strokeLineJoin="round" '
            f'android:pathData="{icon["path"]}" />\n</vector>\n')
        for original in icon['android']:
            java += f'        if (original == R.drawable.{original}) return R.drawable.nebula_settings_{name};\n'
        swift += '        case ' + ', '.join('"' + symbol + '"' for symbol in icon['ios']) + ':\n'
        swift += swift_path(icon['path']) + '\n'
    java += '        return NebulaIcons.previewResource(original, 1);\n    }\n}\n'
    swift += '        default: return nil\n        }\n        path.lineWidth = 1.8\n        path.lineCapStyle = .round\n        path.lineJoinStyle = .round\n        return path\n    }\n}\n'
    outputs[ANDROID / 'java/app/nebulagram/ui/NebulaSettingsIcons.java'] = java
    outputs[IOS / 'NebulaSettingsSymbols.swift'] = swift
    for path, content in outputs.items():
        if args.check:
            assert path.exists() and path.read_text(encoding='utf-8') == content, f'Outdated settings glyph: {path}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    print(f'OK: {len(icons)} original settings glyphs match on Android and iOS')


if __name__ == '__main__':
    main()
