"""Generate only role badges. The Nebula logo and Mira are preserved."""
from pathlib import Path
import argparse
import importlib.util
import json

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location('settings_icons', ROOT / 'scripts/generate-settings-icons.py')
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    roles = json.loads((ROOT / 'design/badges/roles.json').read_text())
    assert set(roles) == {'dev', 'tester', 'heart'}
    swift = '''// Generated by scripts/generate-role-badges.py. Logo and Mira are untouched.
import UIKit
import NebulaSettingsContract

enum NebulaProfileBadgeArtwork {
    static func image(for badge: NebulaBadge) -> UIImage? {
        switch badge {
        case .supporter: return NebulaProfileBadgeImages.supporter
        case .star: return NebulaProfileBadgeImages.star
        default: return vectorImages[badge]
        }
    }
    private static let vectorImages: [NebulaBadge: UIImage] = {
        var result: [NebulaBadge: UIImage] = [:]
        for badge in [NebulaBadge.dev, .tester, .heart] {
            let format = UIGraphicsImageRendererFormat()
            format.scale = 3
            format.opaque = false
            result[badge] = UIGraphicsImageRenderer(size: CGSize(width: 28, height: 28), format: format).image { _ in
                draw(badge)
            }.withRenderingMode(.alwaysOriginal)
        }
        return result
    }()
    private static func color(_ rgb: UInt32) -> UIColor {
        UIColor(red: CGFloat((rgb >> 16) & 255) / 255, green: CGFloat((rgb >> 8) & 255) / 255,
                blue: CGFloat(rgb & 255) / 255, alpha: 1)
    }
    private static func draw(_ badge: NebulaBadge) {
        switch badge {
'''
    outputs = {}
    for role, layers in roles.items():
        xml = '<!-- Generated from design/badges/roles.json. -->\n<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="28dp" android:height="28dp" android:viewportWidth="28" android:viewportHeight="28">\n'
        swift += f'        case .{role}:\n'
        for layer in layers:
            xml += f'    <path android:fillColor="#{layer.get("fill", "00000000")}" '
            if 'stroke' in layer:
                xml += f'android:strokeColor="#{layer["stroke"]}" android:strokeWidth="{layer["width"]}" android:strokeLineCap="round" android:strokeLineJoin="round" '
            xml += f'android:pathData="{layer["path"]}"/>\n'
            swift += '            do {\n            let path = UIBezierPath()\n'
            swift += module.swift_path(layer['path']) + '\n'
            if 'stroke' in layer:
                swift += f'            path.lineWidth = {layer["width"]}\n            path.lineCapStyle = .round\n            path.lineJoinStyle = .round\n            color(0x{layer["stroke"]}).setStroke()\n            path.stroke()\n'
            else:
                swift += f'            color(0x{layer["fill"]}).setFill()\n            path.fill()\n'
            swift += '            }\n'
        outputs[ROOT / f'platform/android/overlay/TMessagesProj/src/main/res/drawable/nebula_badge_{role}.xml'] = xml + '</vector>\n'
    swift += '        default: break\n        }\n    }\n}\n'
    outputs[ROOT / 'platform/ios/overlay/submodules/TelegramUI/Components/PeerInfo/PeerInfoScreen/Sources/NebulaProfileBadgeArtwork.swift'] = swift
    for path, content in outputs.items():
        if args.check:
            assert path.read_text(encoding='utf-8') == content, f'Outdated role badge: {path}'
        else:
            path.write_text(content, encoding='utf-8', newline='\n')
    print('OK: 3 role badges match on Android and iOS; logo and Mira unchanged')

if __name__ == '__main__': main()
