#!/usr/bin/env python3
"""Generate presentation contracts; never rewrite preferences or upstream sources."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / 'shared/settings/catalog.json'
JAVA = ROOT / 'platform/android/overlay/TMessagesProj/src/main/java/app/nebulagram/ui/NebulaSettingsSchema.java'
SWIFT_RESOURCE = ROOT / 'platform/ios/NebulaSettingsContract/Sources/NebulaSettingsContract/Resources/catalog.json'
TYPES = {'boolean': bool, 'integer': int, 'string': str}


def validate_value(row, value):
    if type(value) is not TYPES[row['type']]:
        raise ValueError(f"{row['key']}: wrong type")
    if row['type'] == 'integer' and not row['min'] <= value <= row['max']:
        raise ValueError(f"{row['key']}: outside range")
    if row['type'] == 'string' and len(value.encode('utf-16-le')) // 2 > row['max_length']:
        raise ValueError(f"{row['key']}: string too long")


def validate_catalog(doc):
    if doc['schema_version'] != 1 or doc['transfer_version'] != 1 or doc['transfer_format'] != 'NebulaGram-settings':
        raise ValueError('Unsupported contract version')
    seen = set()
    for row in doc['settings']:
        key = row['key']
        if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', key) or key in seen:
            raise ValueError(f'Duplicate or invalid key: {key}')
        seen.add(key)
        if row['type'] not in TYPES or type(row['transfer_v1']) is not bool:
            raise ValueError(f'Invalid type/transfer flag: {key}')
        if row['android_store'] not in ('nebulagram', 'mainconfig'):
            raise ValueError(f'Unreviewed storage: {key}')
        if row['ios_status'] not in ('planned', 'implemented', 'unsupported'):
            raise ValueError(f'Invalid iOS status: {key}')
        if row['ios_mapping'] not in ('native', 'adapt', 'platform-specific'):
            raise ValueError(f'Invalid iOS mapping: {key}')
        if not re.fullmatch(r'[A-Za-z0-9]+\.java', row['android_source']) or not row['feature']:
            raise ValueError(f'Missing owner: {key}')
        if row['type'] == 'integer':
            if type(row.get('min')) is not int or type(row.get('max')) is not int or not -2147483648 <= row['min'] <= row['max'] <= 2147483647:
                raise ValueError(f'Invalid integer bounds: {key}')
        if row['type'] == 'string' and (type(row.get('max_length')) is not int or not 0 < row['max_length'] <= 1024):
            raise ValueError(f'Invalid string limit: {key}')
        if 'default' in row:
            validate_value(row, row['default'])
        elif not row.get('default_policy'):
            raise ValueError(f'Missing default policy: {key}')


def outputs(doc):
    validate_catalog(doc)
    java_types = {'boolean': 'Boolean', 'integer': 'Integer', 'string': 'String'}
    lines = [
        'package app.nebulagram.ui;', 'import java.util.*;',
        '// Generated by scripts/generate-settings-contract.py. Edit shared/settings/catalog.json.',
        '/** Presentation v1 allowlist only; credentials/internal state are excluded. */',
        'public final class NebulaSettingsSchema {',
        '    public static final int CONTRACT_VERSION = 1;',
        '    public static final Map<String, Class<?>> types;',
        '    static {', '        Map<String, Class<?>> map = new HashMap<>();'
    ]
    for row in sorted(doc['settings'], key=lambda r: r['key']):
        if row['transfer_v1']:
            lines.append(f'        map.put("{row["key"]}", {java_types[row["type"]]}.class);')
    lines += ['        types = Collections.unmodifiableMap(map);', '    }', '}', '']
    return {JAVA: '\n'.join(lines), SWIFT_RESOURCE: json.dumps(doc, ensure_ascii=False, indent=2) + '\n'}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail on stale generated files, write nothing')
    args = parser.parse_args()
    doc = json.loads(CATALOG.read_text(encoding='utf-8'))
    stale = []
    for path, content in outputs(doc).items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    if stale:
        raise SystemExit('Run python scripts/generate-settings-contract.py; stale: ' + ', '.join(stale))
    print(f'{len(doc["settings"])} settings: contracts ' + ('verified' if args.check else 'generated'))


if __name__ == '__main__':
    main()
